### PR TITLE
Fixed #5

### LINKED ISSUE #5: rename_file.webhdfs is not working for absolute path
`rename_file(fs, "foo", "/user/<username>/bar/foo")` is not working due to the fact that `toPath` starts with "^/" and therefore `grep("^/", toPath, invert=TRUE)` returns an integer of length zero (`integer(0)`) why the surrounding `if` complains with `argument is of length zero`
It's already fixed locally and I created a pull request (#6).

### PR DESCRIPTION
**Pull request by nachti**
Bugfix (see Issue #5)

Additional comment: Maybe it would be fine to be consistent with the help files e.g. `rename_file` has one (preferred), `read_file` and others have one for each method.

I didn't increase the version number - It's your decision to do it or not.

### CODE REVIEW

**Comment by saurfang** [comment]
Sorry for the delay and I didn't realize this blocks #13. Would you be interested to rebase this PR?

**Comment by saurfang** [comment]
@antbbn Feel free to open a new PR based on @nachti's work. I just noticed this PR was from 2017 😢

**Comment by nachti** [comment]
i already merged it, so you can just accept the PR. I think there is no need to rebase, is it?
See also https://medium.com/@fredrikmorken/why-you-should-stop-using-git-rebase-5552bee4fed1

**Comment by antbbn** [comment]
Since #13 was merged before this PR and depends on it I understand that he asked me to rebase (or make a new PR) to make sure that `master` is in a working state.
I think he thought that since the pull request was old you might not be interested in pulling `master` to solve the conflicts and update the PR.

Let me know if I can help in any way.

**Comment by nachti** [comment]
Tried to clean it (with some rebase overhead - sorry for that). HTH.
@antbbn: Please add your mail to DESCRIPTION.
Increased the version.

**Comment by antbbn** [comment]
I added my email as requested, thanks :)

**Comment by saurfang** [comment]
Feel free to open new PR if you would like to add your email @antbbn

**Pull request merged**
